language: node_js

node_js:
  - 10

script:
  - cd ./greeting-service
  - npm install --silent
  - npm run ci
  - cd ..
  - cd cute-name-service
  - npm install --silent
  - npm run ci
branches:
  only:
    - master
    - /^greenkeeper/.*$/
